# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=128)),
                ('Straße', models.CharField(max_length=128)),
                ('Hausnummer', models.CharField(max_length=8)),
                ('PLZ', models.CharField(max_length=5)),
                ('Ort', models.CharField(max_length=128)),
                ('Wohnungen', models.ManyToManyField(to='flat.flat')),
            ],
        ),
    ]
