# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseView',
            fields=[
                ('house_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='house.house')),
            ],
            bases=(django.views.generic.base.TemplateView, 'house.house'),
        ),
    ]
