# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
        ('house', '0002_houseview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Wohnungen',
        ),
        migrations.AddField(
            model_name='house',
            name='Wohnungen',
            field=models.ForeignKey(default=9999999999, on_delete=django.db.models.deletion.CASCADE, to='flat.flat'),
            preserve_default=False,
        ),
    ]
