# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
        ('house', '0003_auto_20171020_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Wohnungen',
        ),
        migrations.AddField(
            model_name='house',
            name='Wohnungen',
            field=models.ManyToManyField(to='flat.flat'),
        ),
    ]
