# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20171020_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Wohnungen',
        ),
    ]
