# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_house_wohnungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Bild',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
