# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_house_wohnungen'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Haus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
            preserve_default=False,
        ),
    ]
