# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_flat_haus'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Beschreibung',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='Bild',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
