# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_auto_20171020_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='Fläche',
            field=models.CharField(default='50qm', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='Kaltmiete',
            field=models.CharField(default='500€', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='Objektnummer',
            field=models.CharField(default='42', max_length=32),
            preserve_default=False,
        ),
    ]
